[phases.setup]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python manage.py migrate"

[phases.start]
cmd = "gunicorn app.wsgi:application --bind 0.0.0.0:8000"

[variables]
ENV = "production"
DJANGO_SETTINGS_MODULE = "app.settings"
PORT = "8000"
PYTHONUNBUFFERED = "1"

[dependencies]
runtime = "python"