// Import components
import Head from 'next/head';

// Import layout
import MainLayout from '@/layouts/MainLayout';

// Import stores
import InterfaceStore from '@/stores/InterfaceStore';
const interfaceData = InterfaceStore;

function Contacts({ interfaceData }) {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout data={interfaceData}>
        <>Contacts</>
      </MainLayout>
    </>
  );
}

export default Contacts;

export const getServerSideProps = async (context) => {
  const { locale } = context;
  const currentLocale = locale;

  // При рендере страницы запрашиваем данные из файла с данными.
  await interfaceData.fetchData(currentLocale);

  return {
    props: {
      interfaceData: interfaceData.data,
    },
  };
};
