// Import components
import Head from 'next/head';

// Import components only for this page
import IndexHeader from '@/components/pages/index/IndexHeader/IndexHeader';
import Benefits from '@/components/pages/index/Benefits/Benefits';
import CasesPreview from '@/components/pages/index/CasesPreview/CasesPreview';
import ServicesPreview from '@/components/pages/index/ServicesPreview/ServicesPreview';
import HowWork from '@/components/pages/index/HowWork/HowWork';
import MyTeam from '@/components/pages/index/MyTeam/MyTeam';
import NewsPreview from '@/components/pages/index/NewsPreview/NewsPreview';

// Import common components
import Menu from '@/components/common/Menu/Menu';

// Import stores
import InterfaceStore from '@/stores/InterfaceStore';
const interfaceData = InterfaceStore;

import IndexStore from '@/stores/IndexStore';
const indexData = IndexStore;

import CasesStore from '@/stores/CasesStore';
const casesData = CasesStore;

import ServicesStore from '@/stores/ServicesStore';
const servicesStore = ServicesStore;

import NewsStore from '@/stores/NewsStore';
const newsStore = NewsStore;

function Home({ interfaceData, indexData, casesData, servicesData, newsData }) {
  return (
    <>
      <Head>
        <title>FLOW EXPERT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu
        menuData={interfaceData.topMenu}
        timeData={interfaceData.interface.time}
      />
    </>
  );
}

export default Home;

export const getServerSideProps = async (context) => {
  // Способ узнать текущий язык браузера.
  const { locale } = context;
  const currentLocale = locale;

  // При рендере страницы запрашиваем данные из файла с данными.
  await interfaceData.fetchData(currentLocale);
  await indexData.fetchData(currentLocale);
  await casesData.fetchPreviewData(currentLocale);
  await servicesStore.fetchData(currentLocale);
  await newsStore.fetchPreviewData(currentLocale);

  return {
    props: {
      interfaceData: interfaceData.data,
      indexData: indexData.data,
      casesData: casesData.dataPreviewItems,
      servicesData: servicesStore.data,
      newsData: newsStore.dataPreviewItems,
    },
  };
};
