// Import components
import Head from 'next/head';
import Image from 'next/image';

// Import components only for this page
import IndexHeader from '@/components/pages/index/IndexHeader/IndexHeader';
import Benefits from '@/components/pages/index/Benefits/Benefits';
import CasesPreview from '@/components/pages/index/CasesPreview/CasesPreview';

// Import common components
import Menu from '@/components/common/Menu/Menu';

// Import stores
import InterfaceStore from '@/stores/InterfaceStore';
const interfaceData = InterfaceStore;

import IndexStore from '@/stores/IndexStore';
const indexData = IndexStore;

import CasesStore from '@/stores/CasesStore';
const casesData = CasesStore;

function Home({ interfaceData, indexData, casesData }) {
  return (
    <>
      <Head>
        <title>FLOW EXPERT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu
        menuData={interfaceData.topMenu}
        timeData={interfaceData.interface.time}
      />
      <IndexHeader headerData={indexData.header} />
      <Benefits benefitsData={indexData.benefits} />
      <CasesPreview casesData={casesData} indexData={indexData.cases} />
    </>
  );
}

export default Home;

export const getServerSideProps = async (context) => {
  const { locale } = context;
  const currentLocale = locale;

  // При рендере страницы запрашиваем данные из файла с данными.
  await interfaceData.fetchData(currentLocale);
  await indexData.fetchData(currentLocale);
  await casesData.fetchPreviewData(currentLocale);

  return {
    props: {
      interfaceData: interfaceData.data,
      indexData: indexData.data,
      casesData: casesData.dataPreviewItems,
    },
  };
};
